apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "joanie.fullname" . }}-dotenv
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "joanie.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: joanie
  {{- if .Values.commonAnnotations }}
  annotations: {{ toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
data:
  DJANGO_SILENCED_SYSTEM_CHECKS: "security.W008,security.W004"
