apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "joanie.fullname" . }}-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "joanie.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: joanie
  annotations:
{{- if .Values.commonAnnotations }}
{{- toYaml .Values.commonAnnotations | nindent 4 }}
{{- end }}
{{- if .Values.ingress.acmeIssuerName }}
    cert-manager.io/issuer: {{ .Values.ingress.acmeIssuerName }}
{{- end }}
{{- if .Values.ingress.activateHttpBasicAuth }}
    nginx.ingress.kubernetes.io/auth-type: basic 
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.ingress.htpasswdSecretName }}
    nginx.ingress.kubernetes.io/auth-realm: {{ .Values.ingress.httpBasicAuthMessage }}
{{- end }}
{{- if  and .Values.ingress.activateHttpBasicAuth .Values.ingress.bypassHtaccessIpWhitelist }}
    nginx.ingress.kubernetes.io/satisfy: "any"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," .Values.ingress.bypassHtaccessIpWhitelist }}
{{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ include "joanie.host" . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "joanie.fullname" . }}
            port:
              number: {{ .Values.service.port }}
  tls:
    - hosts:
      - {{ include "joanie.host" .  }}
      secretName: {{ .Values.ingress.tlsSecretName }}
---
{{ if .Values.ingress.adminIpWhitelist }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "joanie.fullname" . }}-ingress-admin
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "joanie.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: joanie
  annotations:
{{- if .Values.ingress.acmeIssuerName -}}
    cert-manager.io/issuer: {{ .Values.ingress.acmeIssuerName }}
{{ end }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," .Values.ingress.adminIpWhitelist }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ include "joanie.host" . | quote }}
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: {{ include "joanie.fullname" . }}
            port:
              number: {{ .Values.service.port }}
  tls:
    - hosts:
      - {{ include "joanie.host" .  }}
      secretName: {{ .Values.ingress.tlsSecretName }}
{{ end }}
