apiVersion: v1
kind: Secret
metadata:
  name: {{ include "joanie.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "joanie.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: joanie
  annotations: 
{{- if .Values.commonAnnotations }}
{{- toYaml .Values.commonAnnotations | nindent 4 }}
{{- end }}
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-weight": "0"
data:
  DJANGO_JWT_PRIVATE_SIGNING_KEY: {{ ( default "" .Values.DjangoJwtPrivateSigningKey ) | quote | b64enc }}
  DJANGO_SECRET_KEY: {{ default "" .Values.DjangoSecretKey | b64enc }}
  {{ if .Values.DjangoSentryDsn }}
  DJANGO_SENTRY_DSN: {{ .Values.DjangoSentryDsn | b64enc }}
  {{ end }}
