"""
URL patterns for Debug views to preview template (certificate, degree, invoice, or a contract
definition) which is enable when settings.DEBUG is True exclusively.
"""

from django.urls import path

from joanie.debug.views import (
    DebugCertificateTemplateView,
    DebugContractTemplateView,
    DebugContractUnicampTemplateView,
    DebugDegreeTemplateView,
    DebugInvitationSignatureLinkHtml,
    DebugInvitationSignatureLinkTxt,
    DebugInvoiceTemplateView,
    DebugMailAllInstallmentPaidViewHtml,
    DebugMailAllInstallmentPaidViewTxt,
    DebugMailInstallmentRefusedPaymentViewHtml,
    DebugMailInstallmentRefusedPaymentViewTxt,
    DebugMailInstallmentReminderPaymentViewHtml,
    DebugMailInstallmentReminderPaymentViewTxt,
    DebugMailSuccessInstallmentPaidViewHtml,
    DebugMailSuccessInstallmentPaidViewTxt,
    DebugMailSuccessPaymentViewBatchOrderHtml,
    DebugMailSuccessPaymentViewBatchOrderTxt,
    DebugMailSuccessPaymentViewHtml,
    DebugMailSuccessPaymentViewTxt,
    DebugMicrocredentialDegreeDefaultTemplateView,
    DebugMicrocredentialDegreeUnicampTemplateView,
    DebugPaymentTemplateView,
    DebugQuoteTemplateView,
)

urlpatterns = [
    path(
        "__debug__/mail/order_validated_html",
        DebugMailSuccessPaymentViewHtml.as_view(),
        name="debug.mail.order_validated_html",
    ),
    path(
        "__debug__/mail/order_validated_txt",
        DebugMailSuccessPaymentViewTxt.as_view(),
        name="debug.mail.order_validated_txt",
    ),
    path(
        "__debug__/mail/invitation_to_sign_contract_html",
        DebugInvitationSignatureLinkHtml.as_view(),
        name="debug.mail.invitation_to_sign_contract_html",
    ),
    path(
        "__debug__/mail/invitation_to_sign_contract_txt",
        DebugInvitationSignatureLinkTxt.as_view(),
        name="debug.mail.invitation_to_sign_contract_txt",
    ),
    path(
        "__debug__/pdf-templates/certificate",
        DebugCertificateTemplateView.as_view(),
        name="debug.certificate_definition.certificate",
    ),
    path(
        "__debug__/pdf-templates/degree",
        DebugDegreeTemplateView.as_view(),
        name="debug.certificate_definition.degree",
    ),
    path(
        "__debug__/pdf-templates/contract-unicamp",
        DebugContractUnicampTemplateView.as_view(),
        name="debug.contract_unicamp.definition",
    ),
    path(
        "__debug__/pdf-templates/microcredential-degree-unicamp",
        DebugMicrocredentialDegreeUnicampTemplateView.as_view(),
        name="debug.certificate_definition.microcredential_degree_unicamp",
    ),
    path(
        "__debug__/pdf-templates/microcredential-degree-default",
        DebugMicrocredentialDegreeDefaultTemplateView.as_view(),
        name="debug.certificate_definition.microcredential_degree_default",
    ),
    path(
        "__debug__/pdf-templates/contract",
        DebugContractTemplateView.as_view(),
        name="debug.contract.definition",
    ),
    path(
        "__debug__/pdf-templates/quote",
        DebugQuoteTemplateView.as_view(),
        name="debug.quote.definition",
    ),
    path(
        "__debug__/pdf-templates/invoice",
        DebugInvoiceTemplateView.as_view(),
        name="debug.invoice_template.invoice",
    ),
    path(
        "__debug__/payment",
        DebugPaymentTemplateView.as_view(),
        name="debug.payment_template",
    ),
    path(
        "__debug__/mail/installment-paid-html",
        DebugMailSuccessInstallmentPaidViewHtml.as_view(),
        name="debug.mail.installment_paid_html",
    ),
    path(
        "__debug__/mail/installment-paid-txt",
        DebugMailSuccessInstallmentPaidViewTxt.as_view(),
        name="debug.mail.installment_paid_txt",
    ),
    path(
        "__debug__/mail/installments-fully-paid-html",
        DebugMailAllInstallmentPaidViewHtml.as_view(),
        name="debug.mail.installments_fully_paid_html",
    ),
    path(
        "__debug__/mail/installments-fully-paid-txt",
        DebugMailAllInstallmentPaidViewTxt.as_view(),
        name="debug.mail.installments_fully_paid_txt",
    ),
    path(
        "__debug__/mail/installment-refused-html",
        DebugMailInstallmentRefusedPaymentViewHtml.as_view(),
        name="debug.mail.installment_refused_html",
    ),
    path(
        "__debug__/mail/installment-refused-txt",
        DebugMailInstallmentRefusedPaymentViewTxt.as_view(),
        name="debug.mail.installment_refused_txt",
    ),
    path(
        "__debug__/mail/installment-reminder-html",
        DebugMailInstallmentReminderPaymentViewHtml.as_view(),
        name="debug.mail.installment_reminder_html",
    ),
    path(
        "__debug__/mail/installment-reminder-txt",
        DebugMailInstallmentReminderPaymentViewTxt.as_view(),
        name="debug.mail.installment_reminder_txt",
    ),
    path(
        "__debug__/mail/batch-order-payment-success-html",
        DebugMailSuccessPaymentViewBatchOrderHtml.as_view(),
        name="debug.mail.batch_order_payment_success_html",
    ),
    path(
        "__debug__/mail/batch-order-payment-success-txt",
        DebugMailSuccessPaymentViewBatchOrderTxt.as_view(),
        name="debug.mail.batch_order_payment_success_txt",
    ),
]
