# Generated by Django 4.0.6 on 2022-07-28 09:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the badge as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("FAK", "Fak"), ("OBF", "Obf")],
                        db_index=True,
                        editable=False,
                        help_text="Should be filled with configured provider name/code for this badge",
                        max_length=3,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "iri",
                    models.URLField(
                        db_index=True,
                        editable=False,
                        help_text="Generated badge IRI, usually the URL pointing to the badge created for a provider",
                        unique=True,
                        verbose_name="IRI",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time at which a badge was created",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time at which a badge was last updated",
                        verbose_name="Updated on",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "db_table": "joanie_badge",
                "ordering": ["created_on"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IssuedBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key for the badge as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iri",
                    models.URLField(
                        editable=False,
                        help_text="Issued badge IRI, usually the URL pointing to issued badge",
                        verbose_name="Issued badge IRI",
                    ),
                ),
                (
                    "resource_link",
                    models.URLField(
                        blank=True,
                        editable=False,
                        help_text="Link to the resource the badge has been issued for (e.g. a course session)",
                        verbose_name="Resource link",
                    ),
                ),
                (
                    "assertion",
                    models.JSONField(
                        blank=True,
                        editable=False,
                        help_text="A JSON object allowing to verify an issued badge",
                        null=True,
                        verbose_name="Issued badge assertion",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time at which an issued badge was created",
                        verbose_name="Created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time at which an issued badge was last updated",
                        verbose_name="Updated on",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="issued",
                        to="badges.badge",
                        verbose_name="Badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issued badge",
                "verbose_name_plural": "Issued badges",
                "db_table": "joanie_issued_badge",
                "ordering": ["created_on"],
            },
        ),
        migrations.CreateModel(
            name="BadgeTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        editable=False,
                        help_text="Should be filled with the badge name from configured provider",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        editable=False,
                        help_text="Should be filled with the badge description from configured provider",
                        verbose_name="Description",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="badges.badge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge Translation",
                "db_table": "joanie_badge_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
