# Generated by Django 3.1.6 on 2021-02-22 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, unique=True, verbose_name='name')),
                ('template', models.CharField(blank=True, max_length=255, null=True, verbose_name='template to generate pdf')),
            ],
            options={
                'verbose_name': 'Certificate definition',
                'verbose_name_plural': 'Certificate definitions',
                'db_table': 'joanie_certificate_definition',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='reference to cms page')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'joanie_course',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='price')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_products', to='core.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'Course product',
                'verbose_name_plural': 'Course products',
                'db_table': 'joanie_course_product',
            },
        ),
        migrations.CreateModel(
            name='CourseRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='resource link')),
                ('start', models.DateTimeField(verbose_name='start date')),
                ('end', models.DateTimeField(verbose_name='end date')),
                ('enrollment_start', models.DateTimeField(null=True, verbose_name='enrollment date')),
                ('enrollment_end', models.DateTimeField(null=True, verbose_name='enrollment end')),
            ],
            options={
                'verbose_name': 'Course run',
                'verbose_name_plural': 'Course runs',
                'db_table': 'joanie_course_run',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'joanie_organization',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('type', models.CharField(choices=[('credential', 'Credential'), ('enrollment', 'Enrollment'), ('certificate', 'Certificate')], max_length=50, verbose_name='type')),
                ('name', models.SlugField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'joanie_product',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('payment_token', models.CharField(blank=True, max_length=255, verbose_name='payment token')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'joanie_user',
            },
        ),
        migrations.CreateModel(
            name='ProductCourseRunPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='position in product')),
                ('course_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_runs_positions', to='core.courseproduct', verbose_name='course product')),
                ('course_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.courserun', verbose_name='course run')),
            ],
            options={
                'verbose_name': 'Position of course runs in course product',
                'verbose_name_plural': 'Positions of course runs in course product',
                'db_table': 'joanie_product_course_run',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='pending', max_length=50, verbose_name='type')),
                ('course_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='core.courseproduct', verbose_name='course product')),
                ('course_runs', models.ManyToManyField(to='core.CourseRun')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='core.user', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'joanie_order',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('validated', 'Validated'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=50, verbose_name='state')),
                ('course_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.courserun', verbose_name='course run')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.order')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'joanie_enrollment',
            },
        ),
        migrations.CreateModel(
            name='CourseProductCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.certificatedefinition', verbose_name='certificate definition')),
                ('course_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.courseproduct', verbose_name='course product')),
            ],
            options={
                'verbose_name': 'Course product certification',
                'verbose_name_plural': 'Course product certifications',
                'db_table': 'joanie_course_product_certification',
            },
        ),
        migrations.AddField(
            model_name='courseproduct',
            name='course_runs',
            field=models.ManyToManyField(to='core.CourseRun'),
        ),
        migrations.AddField(
            model_name='courseproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organization'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
                ('issued_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='issued on date')),
                ('certificate_definition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certificates_issued', to='core.certificatedefinition')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.order')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'joanie_certificate',
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('call_to_action_label', models.CharField(max_length=255, verbose_name='call to action label')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Translation',
                'db_table': 'joanie_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.organization')),
            ],
            options={
                'verbose_name': 'Organization Translation',
                'db_table': 'joanie_organization_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.course')),
            ],
            options={
                'verbose_name': 'Course Translation',
                'db_table': 'joanie_course_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseRunTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.courserun')),
            ],
            options={
                'verbose_name': 'Course run Translation',
                'db_table': 'joanie_course_run_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='courseproduct',
            unique_together={('product', 'course')},
        ),
        migrations.CreateModel(
            name='CertificateDefinitionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.certificatedefinition')),
            ],
            options={
                'verbose_name': 'Certificate definition Translation',
                'db_table': 'joanie_certificate_definition_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
