# Generated by Django 3.1.6 on 2021-03-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='core.order'),
        ),
    ]
