# Generated by Django 3.2 on 2021-06-04 23:57

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="main",
            field=models.BooleanField(default=False, verbose_name="main"),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_ref",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="invoice reference"
            ),
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(
                help_text="Tick to enroll the user to the course run.",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("set", "Set"), ("failed", "Failed")],
                max_length=50,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="tax exclude",
                max_digits=9,
                verbose_name="price (€)",
            ),
        ),
    ]
