# Generated by Django 4.0.3 on 2022-03-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="is_gradable",
            field=models.BooleanField(default=False, verbose_name="is gradable"),
        ),
    ]
