# Generated by Django 3.1.7 on 2021-04-02 13:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                ("postcode", models.CharField(max_length=50, verbose_name="postcode")),
                ("city", models.CharField(max_length=255, verbose_name="city")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="country"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "db_table": "joanie_address",
            },
        ),
    ]
