# Generated by Django 3.1.7 on 2021-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="main",
            field=models.BooleanField(default=False, verbose_name="main"),
        ),
    ]
