# Generated by Django 4.0.3 on 2022-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_courserun_is_gradable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="order",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="orders",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="enrollments",
                to="core.order",
                verbose_name="orders",
            ),
        ),
    ]
