# Generated by Django 4.0.8 on 2023-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_organization_representative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lead_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teaches_in',
        ),
        migrations.AddField(
            model_name='organization',
            name='representative',
            field=models.CharField(blank=True, help_text='representative fullname (to sign certificate for example)', max_length=100, verbose_name='representative'),
        ),
        migrations.AddField(
            model_name='organization',
            name='signature',
            field=models.ImageField(blank=True, upload_to='', verbose_name='signature'),
        ),
    ]
