# Generated by Django 3.2 on 2021-06-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210604_2357"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="certificate_definition",
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, upload_to="", verbose_name="logo"),
        ),
        migrations.AddField(
            model_name="organization",
            name="representative",
            field=models.CharField(
                blank=True,
                help_text="representative fullname (to sign certificate for example)",
                max_length=100,
                verbose_name="representative",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="signature",
            field=models.ImageField(blank=True, upload_to="", verbose_name="signature"),
        ),
    ]
