# Generated by Django 4.0.10 on 2023-02-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_alter_courserun_is_listed_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='action_type',
            new_name='notif_type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_object_ctype',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'producttargetcourserelation')), models.Q(('app_label', 'core'), ('model', 'courserun')), models.Q(('app_label', 'core'), ('model', 'product')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='object_ctype_of_notifications', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_subject_ctype',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'coursewish')), models.Q(('app_label', 'core'), ('model', 'enrollment')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='subject_ctype_of_notifications', to='contenttypes.contenttype'),
        ),
    ]
