# Generated by Django 3.2 on 2021-07-29 04:30

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210607_0938"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("token", models.CharField(max_length=128, verbose_name="token")),
                (
                    "expiration_date",
                    models.DateField(db_index=True, verbose_name="expiration date"),
                ),
                (
                    "last_numbers",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{4}$", "Enter a valid value (4 digits)"
                            )
                        ],
                        verbose_name="last numbers",
                    ),
                ),
                ("main", models.BooleanField(default=False, verbose_name="main")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditcards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit card",
                "verbose_name_plural": "Credit cards",
                "db_table": "joanie_credit_card",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                    ("failed", "Failed"),
                    ("payment_failed", "Payment failed"),
                    ("paid", "Paid"),
                    ("finished", "Finished"),
                ],
                default="pending",
                max_length=50,
                verbose_name="type",
            ),
        ),
    ]
