# Generated by Django 3.2 on 2021-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_address_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_ref",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="invoice reference"
            ),
        ),
    ]
