# Generated by Django 4.0.10 on 2023-04-24 09:21

from django.db import migrations

import easy_thumbnails.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_course_accesses"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cover",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True, upload_to="", verbose_name="cover"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True, upload_to="", verbose_name="logo"
            ),
        ),
    ]
