# Generated by Django 3.2 on 2021-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_order_invoice_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="tax exclude",
                max_digits=5,
                null=True,
                verbose_name="price (€)",
            ),
        ),
    ]
