# Generated by Django 4.2.2 on 2023-07-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_course_cover_alter_organization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="enrollment_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of enrollments associated to this course run",
                verbose_name="enrollment count",
            ),
        ),
        migrations.AddField(
            model_name="courserun",
            name="max_enrollments",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Maximum number of enrollments for this course run",
                verbose_name="max enrollments",
            ),
        ),
    ]
