# Generated by Django 4.0.10 on 2023-06-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_course_cover_alter_organization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseproductrelation",
            name="max_validated_orders",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="max_validated_orders"
            ),
        ),
    ]
