# Generated by Django 4.2.3 on 2023-08-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_order_total_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="enrollment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.enrollment",
                verbose_name="enrollment",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.order",
                verbose_name="order",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("order__isnull", False), ("enrollment__isnull", True)),
                    models.Q(("order__isnull", True), ("enrollment__isnull", False)),
                    _connector="OR",
                ),
                name="either_order_or_enrollment",
                violation_error_message="Certificate should have either an order or an enrollment",
            ),
        ),
    ]
