# Generated by Django 4.2.3 on 2023-08-03 09:08

import django.db.models.deletion
from django.db import migrations, models


def populate_organization(apps, schema_editor):
    """
    A new field "organization" was added to the Certificate model in the previous migration.
    It was added as a nullable field but we now want to populate it on all pre-existing
    objects, in order to make the field required.
    """
    Certificate = apps.get_model("core", "Certificate")
    for certificate in Certificate.objects.select_related("order").iterator():
        certificate.organization_id = certificate.order.organization_id
        certificate.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_certificate_enrollment_certificate_organization_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_organization, migrations.RunPython.noop),
        # Now that the organization field is populated on all objects, make it required
        migrations.AlterField(
            model_name="certificate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
    ]
