# Generated by Django 4.2.4 on 2023-08-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_certificate_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="enrollment",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.enrollment",
                verbose_name="enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="order",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.order",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="organization",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.course",
                verbose_name="course",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.enrollment",
                verbose_name="enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("course__isnull", False), ("enrollment__isnull", True)),
                    models.Q(("course__isnull", True), ("enrollment__isnull", False)),
                    _connector="OR",
                ),
                name="either_course_or_enrollment",
                violation_error_message="Order should have either a course or an enrollment",
            ),
        ),
    ]
