# Generated by Django 4.2.4 on 2023-09-13 21:27

import uuid

import django.db.models.deletion
from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_order_enrollment_alter_certificate_enrollment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseproductrelation",
            name="max_validated_orders",
        ),
        migrations.AlterField(
            model_name="order",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="related_orders",
                to="core.enrollment",
                verbose_name="enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                    ("validated", "Validated"),
                ],
                db_index=True,
                default="draft",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="target_courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="target_orders",
                through="core.OrderTargetCourseRelation",
                to="core.course",
                verbose_name="courses",
            ),
        ),
        migrations.CreateModel(
            name="OrderGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "nb_seats",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The maximum number of orders that can be validated for a given order group",
                        verbose_name="Number of seats",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="order_groups",
                        to="core.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="order",
            name="order_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="core.ordergroup",
                verbose_name="order group",
            ),
        ),
    ]
