# Generated by Django 4.2.5 on 2023-09-23 09:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_producttranslation_instructions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("body", models.TextField(blank=True, verbose_name="body")),
                (
                    "language",
                    models.CharField(
                        choices=[("en-us", "English"), ("fr-fr", "French")],
                        help_text="Language of the contract definition",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("contract_definition", "Contract Definition")],
                        default="contract_definition",
                        max_length=255,
                        verbose_name="template name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract definition",
                "verbose_name_plural": "Contract definitions",
                "db_table": "joanie_contract_definition",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "definition_checksum",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        editable=False,
                        help_text="Localized data snapshot on contract signature",
                        null=True,
                        verbose_name="context",
                    ),
                ),
                (
                    "signature_backend_reference",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Reference in the external signature backend",
                    ),
                ),
                (
                    "signed_on",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Date and time of issuance",
                    ),
                ),
                (
                    "submitted_for_signature_on",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Date and time we send the contract to signature provider",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="contracts",
                        to="core.contractdefinition",
                        verbose_name="Contract definition",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "db_table": "joanie_contract",
                "ordering": ["-created_on"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="contract_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.contractdefinition",
                verbose_name="contract definition",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("definition_checksum__isnull", True), ("context", None)),
                    models.Q(
                        models.Q(("definition_checksum", ""), _negated=True),
                        models.Q(("definition_checksum__isnull", True), _negated=True),
                        models.Q(("context", None), _negated=True),
                        models.Q(("context", {}), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="generate_complete",
                violation_error_message="Make sure to complete all fields when generating a contract.",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("signed_on__isnull", False),
                        models.Q(("definition_checksum", ""), _negated=True),
                        models.Q(("definition_checksum__isnull", True), _negated=True),
                        models.Q(("context", None), _negated=True),
                        models.Q(("context", {}), _negated=True),
                    ),
                    ("signed_on__isnull", True),
                    _connector="OR",
                ),
                name="signed_on_complete",
                violation_error_message="Make sure to complete all fields before signing contract.",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("signed_on__isnull", False),
                    ("submitted_for_signature_on__isnull", False),
                    _negated=True,
                ),
                name="reference_datetime_not_both_set",
                violation_error_message="Make sure to not have both datetime fields set simultaneously.",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("signed_on__isnull", False),
                    ("submitted_for_signature_on__isnull", False),
                    ("signature_backend_reference__isnull", True),
                    _connector="OR",
                ),
                name="signature_backend_reference_must_have_date",
                violation_error_message="Make sure to have a date attached to the signature backend reference.",
            ),
        ),
    ]
