# Generated by Django 4.2.5 on 2023-10-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_certificatedefinition_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("state", "draft"), ("organization__isnull", False), _connector="OR"
                ),
                name="organization_required_if_not_draft",
                violation_error_message="Order should have an organization if not in draft state",
            ),
        ),
    ]
