# Generated by Django 4.2.6 on 2023-11-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_order_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordergroup",
            name="product",
        ),
        migrations.AddField(
            model_name="ordergroup",
            name="course_product_relation",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="order_groups",
                to="core.courseproductrelation",
                verbose_name="course product relation",
            ),
            preserve_default=False,
        ),
    ]
