# Generated by Django 4.2.7 on 2023-11-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_ordergroup_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroup",
            name="course_product_relation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_groups",
                to="core.courseproductrelation",
                verbose_name="course product relation",
            ),
        ),
    ]
