# Generated by Django 4.2.7 on 2023-12-07 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_contract_signed_on_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='organization_signatory',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='signed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='organization signatory'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization_signed_on',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date and time the organization signed the contract'),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='country'),
        ),
    ]
