# Generated by Django 4.2.7 on 2023-12-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contract_organization_signatory_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='reference_datetime_not_both_set',
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('organization_signed_on__isnull', True), ('student_signed_on__isnull', True)), models.Q(('organization_signed_on__isnull', True), ('student_signed_on__isnull', False), ('submitted_for_signature_on__isnull', False)), models.Q(('organization_signed_on__isnull', False), ('student_signed_on__isnull', False), ('submitted_for_signature_on__isnull', True)), _connector='OR')), name='incoherent_signature_dates', violation_error_message='Signature dates are incoherent.'),
        ),
    ]
