# Generated by Django 4.2.10 on 2024-02-09 15:03

from django.db import migrations, models

def set_consent_to_existing_orders(apps, schema_editor):
    """
    The new Order field `has_consent_to_terms` defaults to False,
    but we want it to be True for all pre-existing objects.
    """
    Order = apps.get_model("core", "Order")
    Order.objects.update(has_consent_to_terms=True)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_siteconfig_siteconfigtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_consent_to_terms',
            field=models.BooleanField(default=False, editable=False, help_text='User has consented to the platform terms and conditions.', verbose_name='has consent to terms'),
        ),
        migrations.RunPython(set_consent_to_existing_orders, migrations.RunPython.noop)
    ]
