# Generated by Django 4.2.10 on 2024-02-27 13:17

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_course_effort_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='localized_context',
            field=models.JSONField(editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Localized data that needs to be frozen on certificate creation', verbose_name='context'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='context',
            field=models.JSONField(blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Localized data snapshot on contract signature', null=True, verbose_name='context'),
        ),
    ]
