# Generated by Django 4.2.11 on 2024-03-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_certificate_localized_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='order',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='core.order', verbose_name='order'),
        ),
    ]
