# Generated by Django 4.2.11 on 2024-03-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_certificate_localized_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_subscribed_to_commercial_newsletter',
            field=models.BooleanField(default=False, verbose_name='has subscribed to commercial newsletter'),
        ),
    ]
