# Generated by Django 4.2.10 on 2024-02-29 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import joanie.core.models.activity_logs
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_certificate_localized_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20, verbose_name='level')),
                ('context', joanie.core.models.activity_logs.ActivityLogContextField(default=dict, verbose_name='context')),
                ('type', models.CharField(choices=[('notification', 'Notification'), ('payment_succeeded', 'Payment succeeded'), ('payment_failed', 'Payment failed')], default='notification', max_length=20, verbose_name='type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'activity_log',
                'verbose_name_plural': 'activity_logs',
            },
        ),
    ]
