# Generated by Django 4.2.11 on 2024-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_subscribed_to_commercial_newsletter',
            field=models.BooleanField(default=False, verbose_name='has subscribed to commercial newsletter'),
        ),
    ]
