# Generated by Django 4.2.10 on 2024-02-29 14:22

from django.db import migrations, models
import joanie.core.models.events


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='read',
        ),
        migrations.AddField(
            model_name='event',
            name='context',
            field=joanie.core.models.events.EventContextField(default=dict, verbose_name='context'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('notification', 'Notification'), ('payment_failed', 'Payment failed')], default='notification', max_length=20, verbose_name='type'),
        ),
    ]
