# Generated by Django 4.2.10 on 2024-02-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_event_read_event_context_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('notification', 'Notification'), ('payment_succeeded', 'Payment succeeded'), ('payment_failed', 'Payment failed')], default='notification', max_length=20, verbose_name='type'),
        ),
    ]
