# Generated by Django 4.2.11 on 2024-04-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_payment_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('validated', 'Validated')], db_index=True, default='draft'),
        ),
    ]
