# Generated by Django 4.2.12 on 2024-05-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_documentimage_certificate_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('validated', 'Validated'), ('pending_payment', 'Pending payment'), ('failed_payment', 'Failed payment'), ('no_payment', 'No payment'), ('completed', 'Completed')], db_index=True, default='draft'),
        ),
    ]
