# Generated by Django 4.2.13 on 2024-05-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('to_save_payment_method', 'To save payment method'), ('to_sign', 'To sign'), ('to_sign_and_to_save_payment_method', 'To sign and to save payment method'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('validated', 'Validated'), ('pending_payment', 'Pending payment'), ('failed_payment', 'Failed payment'), ('no_payment', 'No payment'), ('completed', 'Completed')], db_index=True, default='draft'),
        ),
    ]
