# Generated by Django 4.2.13 on 2024-05-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_creditcard_initial_issuer_transaction_identifier'),
        ('core', '0034_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payment.creditcard', verbose_name='credit card'),
        ),
    ]
