# Generated by Django 4.2.13 on 2024-05-28 09:28

from django.db import migrations


def migrate_order_states(apps, schema_editor):
    Order = apps.get_model("core", "Order")
    Order.objects.filter(state="validated" ).update(state="completed")
    Order.objects.filter(state__in=["pending", "submitted"]).update(state="canceled")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_order_credit_card"),
    ]

    operations = [
        migrations.RunPython(migrate_order_states, migrations.RunPython.noop),
    ]
