# Generated by Django 4.2.13 on 2024-06-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='has_consent_to_terms',
            field=models.BooleanField(db_column='has_consent_to_terms', default=False, editable=False, help_text='User has consented to the platform terms and conditions.', verbose_name='has consent to terms'),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='has_consent_to_terms',
            new_name='_has_consent_to_terms',
        ),
    ]
