# Generated by Django 4.2.13 on 2024-07-02 11:10

from django.db import migrations, models
import joanie.core.fields.schedule


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_order_has_consent_to_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_schedule',
            field=models.JSONField(blank=True, decoder=joanie.core.fields.schedule.OrderPaymentScheduleDecoder, editable=False, encoder=joanie.core.fields.schedule.OrderPaymentScheduleEncoder, help_text='Payment schedule for the order.', null=True, verbose_name='payment schedule'),
        ),
    ]
