# Generated by Django 4.2.13 on 2024-07-03 08:53

from django.db import migrations, models

from joanie.core.utils import file_checksum


def update_context(apps, contract):
    """Generate new context for a contract."""
    DocumentImage = apps.get_model("core", "DocumentImage")

    if (
        not contract.context
        or not contract.context.get("organization")
        or not contract.context.get("organization").get("logo")
    ):
        return

    logo = contract.order.organization.logo
    logo_checksum = file_checksum(logo)
    logo_image, _ = DocumentImage.objects.get_or_create(
        checksum=logo_checksum, defaults={"file": logo}
    )
    contract.definition.images.set([logo_image])

    contract.context["organization"]["logo_id"] = str(logo_image.id)
    del contract.context["organization"]["logo"]


def migrate_contract_contexts(apps, schema_editor):
    """
    Upgrade all contracts contexts. This migration is in charge of
    creating all the DocumentImage instances needed for the contract, set relation
    between contract and those images then update context for each contract.
    """
    Contract = apps.get_model("core", "Contract")
    # Only update contracts that are not fully signed.
    contracts = Contract.objects.all()
    for contract in contracts:
        if (
            contract.organization_signed_on is not None
            and contract.student_signed_on is not None
            and not contract.submitted_for_signature_on
        ):
            contract.context = None
        else:
            update_context(apps, contract)
    Contract.objects.bulk_update(contracts, ["context"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_order_payment_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdefinition",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="contract_definitions",
                to="core.documentimage",
                verbose_name="images",
            ),
        ),
        migrations.RunPython(migrate_contract_contexts, migrations.RunPython.noop),
    ]
