# Generated by Django 4.2.15 on 2024-08-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_order_state'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('owner', 'address', 'postcode', 'city', 'country', 'first_name', 'last_name'), name='unique_address_per_user'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('organization', 'address', 'postcode', 'city', 'country', 'first_name', 'last_name'), name='unique_address_per_organization'),
        ),
    ]
