# Generated by Django 4.2.16 on 2024-10-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_address_unique_address_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatedefinition',
            name='template',
            field=models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('degree', 'Degree')], db_index=True, max_length=255, null=True, verbose_name='template to generate pdf'),
        ),
    ]
