# Generated by Django 4.2.16 on 2024-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_address_unique_address_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('notification', 'Notification'), ('payment_succeeded', 'Payment succeeded'), ('payment_failed', 'Payment failed'), ('payment_refunded', 'Payment refunded')], default='notification', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('to_save_payment_method', 'To save payment method'), ('to_sign', 'To sign'), ('signing', 'Signing'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('pending_payment', 'Pending payment'), ('failed_payment', 'Failed payment'), ('no_payment', 'No payment'), ('completed', 'Completed'), ('refunding', 'Refunding'), ('refunded', 'Refunded')], db_index=True, default='draft'),
        ),
    ]
