# Generated by Django 4.2.16 on 2024-09-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_address_unique_address_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_waived_withdrawal_right',
            field=models.BooleanField(default=False, editable=False, help_text='User has waived to its withdrawal right.', verbose_name='has waived to withdrawal right'),
        ),
    ]
