# Generated by Django 4.2.16 on 2024-10-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_certificatedefinition_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdefinition',
            name='appendix',
            field=models.TextField(blank=True, verbose_name='appendix'),
        ),
    ]
