# Generated by Django 4.2.16 on 2024-10-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_contractdefinition_appendix'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_waived_withdrawal_right',
            field=models.BooleanField(default=False, editable=False, help_text='User has waived their withdrawal right.', verbose_name='has waived their right of withdrawal'),
        ),
    ]
