# Generated by Django 4.2.16 on 2024-11-28 10:50

from django.db import migrations, models
import joanie.core.fields.schedule


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_activitylog_type_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_schedule',
            field=models.JSONField(blank=True, decoder=joanie.core.fields.schedule.OrderPaymentScheduleDecoder, default=list, editable=False, encoder=joanie.core.fields.schedule.OrderPaymentScheduleEncoder, help_text='Payment schedule for the order.', null=True, verbose_name='payment schedule'),
        ),
    ]
