# Generated by Django 4.2.16 on 2024-12-02 17:20

from django.db import migrations, models


def migrate_contract_definition_name(apps, schema_editor):
    """
    Updates all existing ContractDefinition records with the name 'contract_definition'
    to 'contract_definition_unicamp'. This ensures consistency with the new naming convention.
    """
    ContractDefinition = apps.get_model("core", "ContractDefinition")
    ContractDefinition.objects.filter(
        name="contract_definition"
    ).update(name="contract_definition_unicamp")


def rollback_contract_definition_name(apps, schema_editor):
    """
    If we need to rollback, this method should be called to reverse the `contract_definition`
    name to the original ones.
    """
    ContractDefinition = apps.get_model("core", "ContractDefinition")
    ContractDefinition.objects.update(name="contract_definition")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_skill_product_certification_level_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdefinition',
            name='name',
            field=models.CharField(
                choices=[
                    ('contract_definition', 'Contract Definition'),  # Keep existing temporarily
                    ('contract_definition_default', 'Contract Definition Default'),
                    ('contract_definition_unicamp', 'Contract Definition Unicamp'),
                ],
                default='contract_definition_default',
                max_length=255,
                verbose_name='template name'
            ),
        ),
        # Update every existing contract definition objects `name` to be "contract_definition_unicamp"
        migrations.RunPython(migrate_contract_definition_name, rollback_contract_definition_name),
    ]
