# Generated by Django 4.2.16 on 2024-12-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_contractdefinition_name'),
    ]

    operations = [
        # Now we can remove the unused choice
        migrations.AlterField(
            model_name='contractdefinition',
            name='name',
            field=models.CharField(choices=[
                ('contract_definition_default', 'Contract Definition Default'),
                ('contract_definition_unicamp', 'Contract Definition Unicamp'),
            ],
                default='contract_definition_default',
                max_length=255,
                verbose_name='template name'
            ),
        ),
    ]
