# Generated by Django 4.2.18 on 2025-01-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_deprecated_choice_contractdefinition_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_owner_course_product_not_canceled',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_owner_enrollment_product_not_canceled',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('canceled', 'refunding', 'refunded')), _negated=True), fields=('course', 'owner', 'product'), name='unique_owner_course_product_not_canceled_or_not_in_refund_states', violation_error_message='An order for this product and course already exists.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('canceled', 'refunding', 'refunded')), _negated=True), fields=('enrollment', 'owner', 'product'), name='unique_owner_enrollment_product_not_canceled_or_not_in_refund_states', violation_error_message='An order for this product and enrollment already exists.'),
        ),
    ]
