# Generated by Django 4.2.18 on 2025-01-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_unique_constraint_order_when_canceled_or_refund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issued_on'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterField(
            model_name='certificatedefinition',
            name='template',
            field=models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('degree', 'Degree'), ('unicamp-degree', 'Unicamp degree')], db_index=True, max_length=255, null=True, verbose_name='template to generate pdf'),
        ),
    ]
