# Generated by Django 4.2.18 on 2025-01-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='order',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='core.order', verbose_name='order'),
        ),
    ]
