# Generated by Django 4.2.18 on 2025-02-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentimage',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='ordergroup',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_on'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
