# Generated by Django 4.2.18 on 2025-02-11 09:33

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_documentimage_options_alter_ordergroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('amount', models.PositiveSmallIntegerField(blank=True, help_text='Discount amount', null=True, verbose_name='amount')),
                ('rate', models.FloatField(blank=True, help_text='Discount rate', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='rate')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'joanie_discount',
                'ordering': ['created_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('rate__isnull', False), ('amount__isnull', False), _connector='OR'), name='discount_rate_or_amount_required', violation_error_message='Discount rate or amount is required.'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('rate__isnull', True), ('amount__isnull', True), _connector='OR'), name='discount_rate_and_amount_exclusive', violation_error_message='Discount rate and amount are exclusive.'),
        ),
    ]
