# Generated by Django 4.2.18 on 2025-02-06 10:16

import django.core.validators
from django.db import migrations, models


def migrate_order_group_nb_seats_zero_to_none(apps, schema_editor):
    """
    Update order groups where the seat number is 0 to None.
    """
    OrderGroup = apps.get_model("core", "OrderGroup")
    OrderGroup.objects.filter(nb_seats=0).update(nb_seats=None)


def rollback_order_group_nb_seats_none_to_zero(apps, schema_editor):
    """
    Restore order group where number of seats is None to 0.
    """
    OrderGroup = apps.get_model("core", "OrderGroup")
    OrderGroup.objects.filter(nb_seats=None).update(nb_seats=0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_documentimage_options_alter_ordergroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='end',
            field=models.DateTimeField(blank=True, help_text='Date at which the order group activation ends', null=True, verbose_name='order group end datetime'),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Date at which the order group activation begins', null=True, verbose_name='order group start datetime'),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='nb_seats',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='The maximum number of orders that can be validated for a given order group', null=True, verbose_name='Number of seats'),
        ),
        migrations.AddConstraint(
            model_name='ordergroup',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', models.F('end'))), name='check_start_before_end', violation_error_message='Start date cannot be greater than end date'),
        ),
        migrations.RunPython(
            migrate_order_group_nb_seats_zero_to_none,
            rollback_order_group_nb_seats_none_to_zero,
        ),
    ]
