# Generated by Django 4.2.18 on 2025-02-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_ordergroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergroup',
            options={},
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_groups', to='core.discount', verbose_name='discount on the product price for the order group'),
        ),
    ]
