# Generated by Django 4.2.19 on 2025-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_ordergroup_options_ordergroup_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_group',
        ),
        migrations.AddField(
            model_name='order',
            name='order_groups',
            field=models.ManyToManyField(blank=True, related_name='orders', to='core.ordergroup', verbose_name='order group'),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Priority of the order group', null=True, verbose_name='priority'),
        ),
    ]
