# Generated by Django 4.2.19 on 2025-02-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_ordergroup_options_ordergroup_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Priority of the order group', verbose_name='priority'),
        ),
    ]
