# Generated by Django 4.2.19 on 2025-03-10 14:49

from django.db import migrations, models
import django.db.models.deletion
import joanie.core.models.products
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_order_order_group_order_order_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('code', models.CharField(default=joanie.core.models.products.generate_random_code, help_text='Voucher code', max_length=255, verbose_name='code')),
                ('multiple_use', models.BooleanField(default=False, help_text='Voucher can be used multiple times per user.', verbose_name='multiple use')),
                ('multiple_users', models.BooleanField(default=False, help_text='Voucher can be used by multiple users.', verbose_name='multiple users')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vouchers', to='core.discount', verbose_name='discount')),
                ('order_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.ordergroup', verbose_name='order group')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'db_table': 'joanie_voucher',
                'ordering': ['created_on'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.voucher', verbose_name='voucher'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('code', 'order_group'), name='unique_code_order_group', violation_error_message='A voucher with this code already exists for this order group.'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(check=models.Q(('discount__isnull', False), ('order_group__isnull', False), _connector='OR'), name='voucher_discount_or_order_group_required', violation_error_message='Voucher discount or order group is required.'),
        ),
    ]
