# Generated by Django 4.2.19 on 2025-03-31 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_voucher_order_voucher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergroup',
            options={'ordering': ['course_product_relation', 'position']},
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_groups', to='core.discount', verbose_name='Product price discount'),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='end',
            field=models.DateTimeField(blank=True, help_text='Date at which the order group rule ends', null=True, verbose_name='rule ends at'),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Priority', null=True, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Date at which the order group rule starts', null=True, verbose_name='rule starts at'),
        ),
    ]
