# Generated by Django 4.2.19 on 2025-03-31 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_ordergroup_options_alter_ordergroup_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Discount amount', null=True, unique=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.FloatField(blank=True, help_text='Discount rate', null=True, unique=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='rate'),
        ),
    ]
