# Generated by Django 4.2.18 on 2025-03-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_batchorder_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchorder',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('to_sign', 'To sign'), ('signing', 'Signing'), ('pending', 'Pending'), ('failed_payment', 'Failed payment'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='draft'),
        ),
    ]
