# Generated by Django 4.2.18 on 2025-03-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_contract_order_alter_order_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchorder',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('to_sign', 'To sign'), ('signing', 'Signing'), ('pending', 'Pending'), ('failed_payment', 'Failed payment'), ('completed', 'Completed')], db_index=True, default='draft'),
        ),
        migrations.AddConstraint(
            model_name='batchorder',
            constraint=models.CheckConstraint(check=models.Q(('state', 'draft'), ('organization__isnull', False), _connector='OR'), name='required_organization_if_not_draft', violation_error_message='BatchOrder requires organization unless in draft state.'),
        ),
    ]
