# Generated by Django 4.2.20 on 2025-05-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_batchorder_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the order group', max_length=255, null=True, verbose_name='description'),
        ),
    ]
