# Generated by Django 4.2.21 on 2025-05-22 15:38

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_batchorder_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchorder',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('to_sign', 'To sign'), ('signing', 'Signing'), ('quoted', 'Quoted'), ('pending', 'Pending'), ('failed_payment', 'Failed payment'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='draft'),
        ),
        migrations.CreateModel(
            name='BatchOrderQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('reference', models.CharField(db_index=True, editable=False, help_text='Unique reference identifier for the quote.', max_length=40, unique=True)),
                ('localized_context', models.JSONField(editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Localized data that needs to be frozen on quote creation', verbose_name='context')),
                ('name', models.CharField(choices=[('quote_default', 'Quote Default')], default='quote_default', max_length=255, verbose_name='template name')),
                ('batch_order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.batchorder', verbose_name='batch order')),
            ],
            options={
                'verbose_name': 'batch order quote',
                'verbose_name_plural': 'batch order quotes',
                'db_table': 'joanie_batch_order_quote',
            },
        ),
    ]
