# Generated by Django 4.2.20 on 2025-04-22 11:18

from django.db import migrations, models
import joanie.core.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_batchorder_state_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voucher',
            name='unique_code_order_group',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(default=joanie.core.models.products.generate_random_code, help_text='Voucher code', max_length=255, unique=True, verbose_name='code'),
        ),
    ]
