# Generated by Django 4.2.22 on 2025-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_batchorder_required_organization_if_not_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the order group', max_length=255, null=True, verbose_name='description'),
        ),
    ]
