# Generated by Django 4.2.23 on 2025-06-13 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_ordergroup_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('nb_seats', models.PositiveSmallIntegerField(blank=True, default=None, help_text='The maximum number of orders that can be validated for a given offer rule', null=True, verbose_name='Number of seats')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=None, help_text='Priority', null=True, verbose_name='priority')),
                ('start', models.DateTimeField(blank=True, help_text='Date at which the offer rule rule starts', null=True, verbose_name='rule starts at')),
                ('end', models.DateTimeField(blank=True, help_text='Date at which the offer rule rule ends', null=True, verbose_name='rule ends at')),
                ('description', models.CharField(blank=True, help_text='Description of the offer rule', max_length=255, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Offer rule',
                'verbose_name_plural': 'Offer rules',
                'ordering': ['course_product_relation', 'position'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='voucher',
            name='unique_code_order_group',
        ),
        migrations.RemoveConstraint(
            model_name='voucher',
            name='voucher_discount_or_order_group_required',
        ),
        migrations.RemoveField(
            model_name='batchorder',
            name='order_groups',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='order_group',
        ),
        migrations.AddField(
            model_name='offerrule',
            name='course_product_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_rules', to='core.courseproductrelation', verbose_name='course product relation'),
        ),
        migrations.AddField(
            model_name='offerrule',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_rules', to='core.discount', verbose_name='Product price discount'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='offer_rules',
            field=models.ManyToManyField(blank=True, related_name='batch_orders', to='core.offerrule', verbose_name='offer rule'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_rules',
            field=models.ManyToManyField(blank=True, related_name='orders', to='core.offerrule', verbose_name='offer rule'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='offer_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.offerrule', verbose_name='offer rule'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_groups',
            field=models.ManyToManyField(blank=True, related_name='_orders', to='core.ordergroup', verbose_name='order group'),
        ),
        migrations.AddConstraint(
            model_name='offerrule',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', models.F('end'))), name='offer_check_start_before_end', violation_error_message='Start date cannot be greater than end date'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('code', 'offer_rule'), name='unique_code_offer_rule', violation_error_message='A voucher with this code already exists for this offer rule.'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(check=models.Q(('discount__isnull', False), ('offer_rule__isnull', False), _connector='OR'), name='voucher_discount_or_offer_rule_required', violation_error_message='Voucher discount or offer rule is required.'),
        ),
    ]
