# Generated by Django 4.2.23 on 2025-06-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_offerrule_remove_voucher_unique_code_order_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproductrelation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offers', to='core.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='courseproductrelation',
            name='organizations',
            field=models.ManyToManyField(related_name='offers', to='core.organization', verbose_name='organizations'),
        ),
        migrations.AlterField(
            model_name='courseproductrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='ordertargetcourserelation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.order', verbose_name='order'),
        ),
    ]
