# Generated by Django 4.2.21 on 2025-06-13 15:24

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_courseproductrelation_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('fr-fr', 'French')], help_text='Language of the contract definition', max_length=10, verbose_name='language')),
                ('name', models.CharField(choices=[('quote_default', 'Quote Default')], default='quote_default', max_length=255, verbose_name='template name')),
                ('images', models.ManyToManyField(blank=True, editable=False, related_name='quotes', to='core.documentimage', verbose_name='images')),
            ],
            options={
                'verbose_name': 'Quote definition',
                'verbose_name_plural': 'Quote definitions',
                'db_table': 'joanie_quote_definition',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('context', models.JSONField(blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Localized data snapshot of the quote generated', null=True, verbose_name='context')),
                ('organization_signed_on', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date and time organization signed on')),
                ('buyer_signed_on', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date and time buyer signed on')),
                ('has_purchase_order_received', models.BooleanField(default=False, editable=False, help_text='Quote has purchase order to confirm payment from buyer', verbose_name='has received the purchase order to confirm the payment')),
                ('batch_order', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.batchorder', verbose_name='Batch order')),
                ('definition', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='quotes', to='core.quotedefinition', verbose_name='Quote definition')),
            ],
            options={
                'verbose_name': 'batch order quote',
                'verbose_name_plural': 'batch order quotes',
                'db_table': 'joanie_batch_order_quote',
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('organization_signed_on__isnull', True), ('buyer_signed_on__isnull', False), _negated=True), name='organization_must_sign_before_buyer', violation_error_message='Organization must sign quote before the buyer.'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('has_purchase_order_received', True), ('buyer_signed_on__isnull', True), _negated=True), name='both_parties_must_sign_before_purchase_order_accepted', violation_error_message='Both parties must sign quote before confirming the purchase order.'),
        ),
    ]
