# Generated by Django 4.2.23 on 2025-06-23 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_courseproductrelation_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('nb_seats', models.PositiveSmallIntegerField(blank=True, default=None, help_text='The maximum number of orders that can be validated for a given offering rule', null=True, verbose_name='Number of seats')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=None, help_text='Priority', null=True, verbose_name='priority')),
                ('start', models.DateTimeField(blank=True, help_text='Date at which the offering rule rule starts', null=True, verbose_name='rule starts at')),
                ('end', models.DateTimeField(blank=True, help_text='Date at which the offering rule rule ends', null=True, verbose_name='rule ends at')),
                ('description', models.CharField(blank=True, help_text='Description of the offering rule', max_length=255, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Offering rule',
                'verbose_name_plural': 'Offering rules',
                'ordering': ['course_product_relation', 'position'],
            },
        ),
        migrations.RemoveField(
            model_name='offerrule',
            name='course_product_relation',
        ),
        migrations.RemoveField(
            model_name='offerrule',
            name='discount',
        ),
        migrations.RemoveConstraint(
            model_name='voucher',
            name='unique_code_offer_rule',
        ),
        migrations.RemoveConstraint(
            model_name='voucher',
            name='voucher_discount_or_offer_rule_required',
        ),
        migrations.RemoveField(
            model_name='batchorder',
            name='offer_rules',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offer_rules',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='offer_rule',
        ),
        migrations.AlterField(
            model_name='courseproductrelation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offerings', to='core.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='courseproductrelation',
            name='organizations',
            field=models.ManyToManyField(related_name='offerings', to='core.organization', verbose_name='organizations'),
        ),
        migrations.AlterField(
            model_name='courseproductrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='core.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='ordertargetcourserelation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='core.order', verbose_name='order'),
        ),
        migrations.DeleteModel(
            name='OfferRule',
        ),
        migrations.AddField(
            model_name='offeringrule',
            name='course_product_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_rules', to='core.courseproductrelation', verbose_name='course product relation'),
        ),
        migrations.AddField(
            model_name='offeringrule',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offering_rules', to='core.discount', verbose_name='Product price discount'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='offering_rules',
            field=models.ManyToManyField(blank=True, related_name='batch_orders', to='core.offeringrule', verbose_name='offering rule'),
        ),
        migrations.AddField(
            model_name='order',
            name='offering_rules',
            field=models.ManyToManyField(blank=True, related_name='orders', to='core.offeringrule', verbose_name='offering rule'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='offering_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.offeringrule', verbose_name='offering rule'),
        ),
        migrations.AddConstraint(
            model_name='offeringrule',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', models.F('end'))), name='offering_check_start_before_end', violation_error_message='Start date cannot be greater than end date'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('code', 'offering_rule'), name='unique_code_offering_rule', violation_error_message='A voucher with this code already exists for this offering rule.'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(check=models.Q(('discount__isnull', False), ('offering_rule__isnull', False), _connector='OR'), name='voucher_discount_or_offering_rule_required', violation_error_message='Voucher discount or offering rule is required.'),
        ),
    ]
