# Generated by Django 4.2.23 on 2025-06-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_offeringrule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchorder',
            name='offering_rules',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offering_rules',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='offering_rule',
        ),
        migrations.DeleteModel(
            name='OfferingRule',
        ),
    ]
