# Generated by Django 4.2.23 on 2025-07-02 15:13

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_offeringrule_batchorder_offering_rules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('fr-fr', 'French')], help_text='Language of the quote definition', max_length=10, verbose_name='language')),
                ('name', models.CharField(choices=[('quote_default', 'Quote Default')], default='quote_default', max_length=255, verbose_name='template name to generate pdf')),
                ('images', models.ManyToManyField(blank=True, editable=False, related_name='quotes', to='core.documentimage', verbose_name='images')),
            ],
            options={
                'verbose_name': 'Quote definition',
                'verbose_name_plural': 'Quote definitions',
                'db_table': 'joanie_quote_definition',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('context', models.JSONField(blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Localized data snapshot of the quote generated', null=True, verbose_name='context')),
                ('organization_signed_on', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date and time organization signed on')),
                ('buyer_signed_on', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date and time buyer signed on')),
                ('has_purchase_order', models.BooleanField(default=False, editable=False, help_text='Quote has purchase order to confirm payment from buyer', verbose_name='purchase order to confirm payment')),
                ('batch_order', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.batchorder', verbose_name='Batch order')),
                ('definition', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='quotes', to='core.quotedefinition', verbose_name='Quote definition')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'joanie_quote',
            },
        ),
        migrations.CreateModel(
            name='QuoteDefinitionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.quotedefinition')),
            ],
            options={
                'verbose_name': 'Quote definition Translation',
                'db_table': 'joanie_quote_definition_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('organization_signed_on__isnull', True), ('buyer_signed_on__isnull', False), _negated=True), name='organization_must_sign_before_buyer', violation_error_message='Organization must sign quote before the buyer.'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('has_purchase_order', True), ('buyer_signed_on__isnull', True), _negated=True), name='both_parties_must_sign_before_purchase_order_accepted', violation_error_message='Both parties must sign quote before confirming the purchase order.'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('organization_signed_on__isnull', False), ('context', None), _negated=True), name='The quote requires a context', violation_error_message='You must generate the quote context before signing the quote.'),
        ),
    ]
