# Generated by Django 4.2.23 on 2025-07-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_quotedefinition_quote_quotedefinitiontranslation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quote',
            name='organization_must_sign_before_buyer',
        ),
        migrations.RemoveConstraint(
            model_name='quote',
            name='both_parties_must_sign_before_purchase_order_accepted',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='buyer_signed_on',
        ),
        migrations.AlterField(
            model_name='batchorder',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('quoted', 'Quoted'), ('to_sign', 'To sign'), ('signing', 'Signing'), ('pending', 'Pending'), ('failed_payment', 'Failed payment'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='draft'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('organization_signed_on__isnull', True), ('has_purchase_order', True), _negated=True), name='organization_must_sign_quote_before_receiving_purchase_order', violation_error_message='Organization must sign quote before receiving purchase order.'),
        ),
    ]
