# Generated by Django 4.2.23 on 2025-07-18 12:17

from django.db import migrations, models
import joanie.core.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_quotedefinition_quote_quotedefinitiontranslation_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='voucher',
                    name='unique_code_offering_rule',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='batchorder',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('quoted', 'Quoted'), ('to_sign', 'To sign'), ('signing', 'Signing'), ('pending', 'Pending'), ('failed_payment', 'Failed payment'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='draft'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(default=joanie.core.models.products.generate_random_code, help_text='Voucher code', max_length=255, unique=True, verbose_name='code'),
        ),
    ]
