# Generated by Django 4.2.23 on 2025-07-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_quote_organization_must_sign_before_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quote_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.quotedefinition', verbose_name='Quote definition'),
        ),
    ]
