# Generated by Django 4.2.23 on 2025-07-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_product_quote_definition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_on'], 'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
    ]
