# Generated by Django 4.2.23 on 2025-08-19 09:07

from django.db import migrations, models



def migrate_certificate_definition_name(apps, schema_editor):
    """
    Update all existing Certificate Definition records with the name 'unicamp-degree' to
    'microcredential_degree_unicamp'. This ensures consistency with the new naming convention.
    """
    CertificateDefinition = apps.get_model("core", "CertificateDefinition")
    CertificateDefinition.objects.filter(
        name="unicamp-degree"
    ).update(name="microcredential_degree_unicamp")


def rollback_certificate_definition_name(apps, schema_editor):
    """
    If we need to rollback, this method should be called to reverse the
    'microcredential_degree_unicamp' name the original one 'unicamp-degree'.
    """
    CertificateDefinition = apps.get_model("core", "CertificateDefinition")
    CertificateDefinition.objects.update(name="unicamp-degree")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_quote_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatedefinition',
            name='template',
            field=models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('degree', 'Degree'), ('microcredential_degree_default', 'Microcredential Degree Default'), ('microcredential_degree_unicamp', 'Microcredential Degree Unicamp')], db_index=True, max_length=255, null=True, verbose_name='template to generate pdf'),
        ),
        migrations.RunPython(migrate_certificate_definition_name, rollback_certificate_definition_name),
    ]
