# Generated by Django 4.2.23 on 2025-08-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_certificatedefinition_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='reference',
            field=models.CharField(blank=True, help_text='Incremental quote reference number, e.g. FUN_2025_0000001', max_length=20, null=True, unique=True, verbose_name='reference'),
        ),
    ]
