# Generated by Django 4.2.23 on 2025-08-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_certificatedefinition_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchorder',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
