# Generated by Django 4.2.23 on 2025-08-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_quote_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchorder',
            name='payment_method',
            field=models.CharField(choices=[('purchase_order', 'Purchase order'), ('bank_transfer', 'Bank transfer'), ('card_payment', 'Card payment')], db_index=True, default='card_payment'),
        ),
    ]
