# Generated by Django 4.2.23 on 2025-08-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_batchorder_administrative_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchorder',
            name='trainees',
        ),
    ]
