# Generated by Django 4.2.23 on 2025-08-06 15:20

from django.db import migrations, models
import joanie.core.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_voucher_batchorder_voucher_order_voucher_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voucher',
            name='unique_code_offering_rule',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(default=joanie.core.models.products.generate_random_code, help_text='Voucher code', max_length=255, unique=True, verbose_name='code'),
        ),
    ]
