# Generated by Django 4.2.23 on 2025-08-22 13:48

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_batchorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchorder',
            name='administrative_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Administrative email'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='administrative_firstname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Administrative firstname'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='administrative_lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Administrative lastname'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='administrative_profession',
            field=models.CharField(blank=True, help_text='administrative profession representative', max_length=100, null=True, verbose_name='Administrative profession representative'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='administrative_telephone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Administrative phone number'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='billing_address',
            field=models.JSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="billing address if different from company's address", verbose_name='billing address of the company'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, help_text='funding amount of the batch order from the funding entity', max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='funding amount'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='funding_entity',
            field=models.CharField(blank=True, help_text="funding entity's name that helps financially the payment", max_length=255, null=True, verbose_name='funding entity name'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='vat_registration',
            field=models.CharField(blank=True, help_text="company's vat identification number like Numero de TVA intracommunautaire in France", max_length=255, null=True, verbose_name='Tax registration number'),
        ),
    ]
