# Generated by Django 4.2.23 on 2025-09-12 09:43

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_batchorder_administrative_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchorder',
            name='trainees',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='trainees name list', null=True, verbose_name='trainees'),
        ),
    ]
