# Generated by Django 4.2.23 on 2025-08-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_batchorder_trainees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchorder',
            name='voucher',
        ),
    ]
