# Generated by Django 4.2.23 on 2025-09-04 09:35

from django.db import migrations, models
import django.db.models.deletion


def migrate_to_contract_definition_order(apps, schema_editor):
    """
    Forward migration : update on all existing products records the transfer of contract
    definition object to the new field `contract_definition_order` when there is one.
    """
    Product = apps.get_model("core", "Product")
    for product in Product.objects.filter(contract_definition__isnull=False):
        contract_definition = product.contract_definition
        product.contract_definition_order = contract_definition
        product.contract_definition = None
        product.save()


def rollback_to_contract_definition(apps, schema_editor):
    """
    Backward migration : Restore the contract definition object to the field `contract_definition`.
    """
    Product = apps.get_model("core", "Product")
    for product in Product.objects.filter(contract_definition_order__isnull=False):
        contract_definition = product.contract_definition_order
        product.contract_definition = contract_definition
        product.contract_definition_order = None
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_batchorder_trainees'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contract_definition_batch_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_definition_batch_order', to='core.contractdefinition', verbose_name='Contract definition for batch order'),
        ),
        migrations.AddField(
            model_name='product',
            name='contract_definition_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_definition_order', to='core.contractdefinition', verbose_name='Contract definition for single order'),
        ),
        migrations.RunPython(
            migrate_to_contract_definition_order,
            rollback_to_contract_definition,
        ),
        migrations.RemoveField(
            model_name='product',
            name='contract_definition',
        ),
    ]
