# Generated by Django 4.2.23 on 2025-09-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_product_contract_definition_batch_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contract_definition',
        ),
    ]
