# Generated by Django 4.2.23 on 2025-09-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_product_contract_definition_batch_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdefinition',
            name='name',
            field=models.CharField(choices=[('contract_definition_default', 'Contract Definition Default'), ('contract_definition_unicamp', 'Contract Definition Unicamp'), ('professional_training_agreement_default', 'Professional Training Agreement Default'), ('professional_training_agreement_unicamp', 'Professional Training Agreement Unicamp')], default='contract_definition_default', max_length=255, verbose_name='template name'),
        ),
    ]
