# Generated by Django 4.2.23 on 2025-09-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_contractdefinition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchorder',
            name='signatory_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signatory email'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='signatory_firstname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signatory firstname'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='signatory_lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signatory lastname'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='signatory_profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signatory profession'),
        ),
        migrations.AddField(
            model_name='batchorder',
            name='signatory_telephone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Signatory telephone'),
        ),
    ]
