# Generated by Django 4.2.23 on 2025-09-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_batchorder_signatory_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchorder',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
