# Generated by Django 4.2.25 on 2025-10-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_voucher_batchorder_voucher_order_voucher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotedefinitiontranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quotedefinitiontranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='QuoteDefinition',
        ),
        migrations.DeleteModel(
            name='QuoteDefinitionTranslation',
        ),
    ]
