# Generated by Django 4.2.25 on 2025-10-09 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_quotedefinitiontranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('fr-fr', 'French')], help_text='Language of the quote definition', max_length=10, verbose_name='language')),
                ('name', models.CharField(choices=[('quote_default', 'Quote Default')], default='quote_default', max_length=255, verbose_name='template name to generate pdf')),
                ('images', models.ManyToManyField(blank=True, editable=False, related_name='quotes', to='core.documentimage', verbose_name='images')),
            ],
            options={
                'verbose_name': 'Quote definition',
                'verbose_name_plural': 'Quote definitions',
                'db_table': 'joanie_quote_definition',
            },
        ),
    ]
