# Generated by Django 4.2.26 on 2025-11-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_quotedefinition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchorder',
            name='contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='batch_order',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.batchorder', verbose_name='batch_order'),
        ),
    ]
