# Generated by Django 4.2.26 on 2025-11-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_remove_batchorder_contract_contract_batch_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchorder',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('quoted', 'Quoted'), ('to_sign', 'To sign'), ('signing', 'Signing'), ('pending', 'Pending'), ('process_payment', 'Process payment'), ('failed_payment', 'Failed payment'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='draft'),
        ),
    ]
