# Generated by Django 4.2.27 on 2025-12-15 16:56

from django.db import migrations, models


def migrate_signatory_data(apps, schema_editor):
    """
    Migrate existing signatory data to ensure no null values remain.
    """
    BatchOrder = apps.get_model("core", "BatchOrder")
    for batch_order in BatchOrder.objects.all():
        if batch_order.signatory_email is None:
            batch_order.signatory_email = batch_order.owner.email
        if batch_order.signatory_firstname is None:
            batch_order.signatory_firstname = batch_order.owner.first_name
        if batch_order.signatory_lastname is None:
            batch_order.signatory_lastname = batch_order.owner.last_name
        if batch_order.signatory_profession is None:
            batch_order.signatory_profession = ""
        if batch_order.signatory_telephone is None:
            batch_order.signatory_telephone = batch_order.owner.phone_number
        batch_order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_batchorder_state'),
    ]

    operations = [
        migrations.RunPython(migrate_signatory_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='batchorder',
            name='signatory_email',
            field=models.CharField(max_length=100, verbose_name='Signatory email'),
        ),
        migrations.AlterField(
            model_name='batchorder',
            name='signatory_firstname',
            field=models.CharField(max_length=100, verbose_name='Signatory firstname'),
        ),
        migrations.AlterField(
            model_name='batchorder',
            name='signatory_lastname',
            field=models.CharField(max_length=100, verbose_name='Signatory lastname'),
        ),
        migrations.AlterField(
            model_name='batchorder',
            name='signatory_profession',
            field=models.CharField(max_length=100, verbose_name='Signatory profession'),
        ),
    ]
