# Generated by Django 4.2.27 on 2026-01-21 09:36

from django.db import migrations, models


def migrate_purchase_order_reference(apps, schema_editor):
    """
    Update all existing Quote objects with a purchase order reference when the
    related batch order uses purchase order payment method.
    """
    Quote = apps.get_model("core", "Quote")
    for i, quote in enumerate(Quote.objects.all()):
        if quote.batch_order.uses_purchase_order and quote.has_purchase_order:
            quote.purchase_order_reference = f"reference_to_update_{i}"
            quote.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_batchorder_signatory_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='purchase_order_reference',
            field=models.CharField(blank=True, help_text='reference provided by the buyer used for commercial tracking for contract and invoice', max_length=30, null=True, unique=True, verbose_name='purchase_order_reference'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('has_purchase_order', False), models.Q(('organization_signed_on__isnull', False), ('purchase_order_reference__isnull', False)), _connector='OR'), name='purchase_order_requires_signed_and_reference', violation_error_message='If a purchase order is received, the organization must have signed and a purchase order reference must be set.'),
        ),
        migrations.RunPython(
            migrate_purchase_order_reference,
            migrations.RunPython.noop,
        ),
    ]
