# Generated by Django 4.2.28 on 2026-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_quote_purchase_order_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='purchase_order_reference',
            field=models.CharField(blank=True, help_text='reference provided by the buyer used for commercial tracking for contract and invoice', max_length=30, null=True, verbose_name='purchase_order_reference'),
        ),
    ]
