# Generated by Django 4.2.28 on 2026-02-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_quote_purchase_order_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchorder',
            options={'ordering': ['-created_on'], 'verbose_name': 'batch order', 'verbose_name_plural': 'batch orders'},
        ),
    ]
