# Generated by Django 4.2.27 on 2026-02-04 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_batchorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingDeepLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('deep_link', models.URLField(help_text='Deep link of an offering where a learner can subscribe with an external link.', unique=True, verbose_name='deep_link')),
                ('is_active', models.BooleanField(default=False, help_text='Activate or deactivate deep link of an offering', verbose_name='is active')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='core.courseproductrelation', verbose_name='offering')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_links', to='core.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'Offering Deep Link',
                'verbose_name_plural': 'Offering Deep Links',
                'db_table': 'joanie_offering_deep_link',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='offeringdeeplink',
            constraint=models.UniqueConstraint(fields=('organization', 'offering'), name='unique_offering_per_organization'),
        ),
    ]
