# Generated by Django 4.2.29 on 2026-04-02 10:32

from django.db import migrations, models


def backfill_order_nature(apps, schema_editor):
    """Set nature based on existing data: b2b if batch_order, cpf if 100% voucher."""
    Order = apps.get_model("core", "Order")

    Order.objects.filter(batch_order__isnull=False).update(nature="b2b")
    Order.objects.filter(
        batch_order__isnull=True,
        voucher__isnull=False,
        voucher__discount__rate=1,
    ).update(nature="cpf")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_offeringdeeplink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nature',
            field=models.CharField(choices=[('b2c', 'B2C'), ('b2b', 'B2B'), ('cpf', 'CPF')], db_index=True, default='b2c', max_length=3, verbose_name='nature'),
        ),
        migrations.RunPython(
            backfill_order_nature,
            migrations.RunPython.noop,
        ),
    ]
