# Generated by Django 4.2.30 on 2026-05-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_create_admin_order_custom_discount_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeringdeeplink',
            name='deep_link',
            field=models.URLField(help_text='Deep link of an offering where a learner can subscribe with an external link.', max_length=400, unique=True, verbose_name='deep_link'),
        ),
    ]
