# Generated by Django 4.2.30 on 2026-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_offeringdeeplink_deep_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='withdrawn_confirmation_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date and time order is withdrawn'),
        ),
        migrations.AddField(
            model_name='order',
            name='withdrawn_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date and time buyer requested to withdraw the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('to_save_payment_method', 'To save payment method'), ('to_sign', 'To sign'), ('signing', 'Signing'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('pending_withdraw', 'To withdraw'), ('pending_payment', 'Pending payment'), ('failed_payment', 'Failed payment'), ('no_payment', 'No payment'), ('completed', 'Completed'), ('refunding', 'Refunding'), ('refunded', 'Refunded'), ('to_own', 'To own')], db_index=True, default='draft'),
        ),
    ]
