# Generated by Django 5.2.17 on 2026-10-02 13:24

import joanie.core.fields.multiselect
import joanie.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_order_withdrawn_confirmation_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdefinition',
            name='language',
            field=models.CharField(choices=joanie.core.utils.get_language_choices, help_text='Language of the contract definition', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='courses', through='core.CourseProductRelation', through_fields=('course', 'product'), to='core.product', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='languages',
            field=joanie.core.fields.multiselect.MultiSelectField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], help_text='The list of languages in which the course content is available.', max_choices=50, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='target_courses',
            field=models.ManyToManyField(blank=True, related_name='target_orders', through='core.OrderTargetCourseRelation', through_fields=('order', 'course'), to='core.course', verbose_name='courses'),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_courses',
            field=models.ManyToManyField(blank=True, related_name='targeted_by_products', through='core.ProductTargetCourseRelation', through_fields=('product', 'course'), to='core.course', verbose_name='target courses'),
        ),
        migrations.AlterField(
            model_name='quotedefinition',
            name='language',
            field=models.CharField(choices=joanie.core.utils.get_language_choices, help_text='Language of the quote definition', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=joanie.core.utils.get_language_choices, default='en-us', help_text='Language of the user', max_length=10, verbose_name='language'),
        ),
    ]
