# Generated by Django 3.2.7 on 2021-10-15 15:33

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="title"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="brand"
                    ),
                ),
                (
                    "expiration_month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="expiration month",
                    ),
                ),
                (
                    "expiration_year",
                    models.PositiveSmallIntegerField(verbose_name="expiration year"),
                ),
                (
                    "last_numbers",
                    models.CharField(max_length=4, verbose_name="last 4 numbers"),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="main")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "credit card",
                "verbose_name_plural": "credit cards",
                "db_table": "joanie_credit_card",
            },
        ),
        migrations.AddConstraint(
            model_name="creditcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("owner",),
                name="unique_main_credit_card_per_user",
            ),
        ),
    ]
