# Generated by Django 4.0.10 on 2023-04-21 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditcard",
            options={
                "ordering": ["-created_on"],
                "verbose_name": "credit card",
                "verbose_name_plural": "credit cards",
            },
        ),
    ]
