# Generated by Django 4.2.7 on 2023-11-23 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "payment",
            "0003_remove_invoice_main_invoice_should_have_a_positive_amount_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="recipient_address",
            new_name="deprecated_recipient_address",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="recipient_name",
            new_name="deprecated_recipient_name",
        ),
    ]
