# Generated by Django 4.2.10 on 2024-02-27 13:17

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_invoice_deprecated_recipient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='localized_context',
            field=models.JSONField(editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Localized data that needs to be frozen on invoice creation', verbose_name='context'),
        ),
    ]
