# Generated by Django 4.2.11 on 2024-04-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_invoice_localized_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='initial_issuer_transaction_identifier',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='initial issuer transaction identifier'),
        ),
    ]
