# Generated by Django 4.2.17 on 2025-01-10 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_credit_card_owner_to_owners_field(apps, schema_editor):
    """
    Forward migration: Transfer the `owner` field data to the new `owners` ManyToManyField.
    """
    CreditCard = apps.get_model("payment", "CreditCard")
    for card in CreditCard.objects.all():
        if card.owner:
            card.owners.set([card.owner])


def rollback_credit_card_owners_to_primary_owner(apps, schema_editor):
    """
    Backward migration: Restore the `owner` field using the first entry in `owners`.
    """
    CreditCard = apps.get_model("payment", "CreditCard")
    for card in CreditCard.objects.all():
        if card.owners.exists():
            card.owner = card.owners.first()
            card.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0009_creditcard_payment_provider'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creditcard',
            name='unique_main_credit_card_per_user',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='owners',
            field=models.ManyToManyField(related_name='payment_cards', to=settings.AUTH_USER_MODEL, verbose_name='owners'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.RunPython(
            migrate_existing_credit_card_owner_to_owners_field,
            rollback_credit_card_owners_to_primary_owner,
        ),
    ]
