# Generated by Django 4.2.18 on 2025-02-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_creditcardownership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='owner',
        ),
    ]
