# Generated by Django 4.2.18 on 2025-03-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_contract_order_alter_order_owner_and_more'),
        ('payment', '0011_remove_creditcard_is_main_remove_creditcard_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='batch_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.batchorder', verbose_name='batch order'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recipient_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='core.address', verbose_name='invoice address'),
        ),
    ]
