# Generated by Django 5.2.17 on 2026-09-22 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_invoice_batch_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='owners',
            field=models.ManyToManyField(related_name='payment_cards', through='payment.CreditCardOwnership', through_fields=('credit_card', 'owner'), to=settings.AUTH_USER_MODEL, verbose_name='owners'),
        ),
    ]
