# Generated by Django 4.2.29 on 2026-04-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_invoice_batch_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='final_reference',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
